apiVersion: v1
kind: Secret
metadata:
  name: {{ include "eddid-route.fullname" . }}-secret
  labels:
    app: {{ include "eddid-route.name" . }}
    environment: {{ .Values.custom.deployment.environment }}
stringData:
  EUREKA_PASSWORD: {{ required ".secret.EUREKA_PASSWORD entry required!" .Values.secret.EUREKA_PASSWORD }}